// SPDX-License-Identifier: MIT
//! Contract error types for the XLM Price Prediction Market.

use soroban_sdk::contracterror;

/// Contract error types
#[contracterror(export = false)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum ContractError {
    AlreadyInitialized = 1,
    AdminNotSet = 2,
    OracleNotSet = 3,
    InvalidBetAmount = 6,
    NoActiveRound = 7,
    RoundEnded = 8,
    InsufficientBalance = 9,
    AlreadyBet = 10,
    Overflow = 11,
    InvalidPrice = 12,
    InvalidDuration = 13,
    InvalidMode = 14,
    WrongModeForPrediction = 15,
    RoundNotEnded = 16,
    StaleOracleData = 18,
    InvalidOracleRound = 19,
    RoundAlreadyActive = 20,
    ContractPaused = 22,
    WindowOutOfRange = 23,
    FutureOracleData = 24,
    PayoutOverflow = 25,
    RoundNotCancellable = 27,
    StakeExceedsMax = 28,
    ExposureCapExceeded = 29,
    PendingWinningsCapExceeded = 30,
    InvalidStartPrice = 31,
    OracleNonceReused = 33,
    InvalidMinParticipants = 35,
    InvalidPrecisionCap = 38,
    PrecisionCapExceeded = 39,
    OracleDeviationExceeded = 41,
    UnsupportedSchemaVersion = 42,
    MigrationActiveRound = 44,
    CommitmentNotFound = 45,
    AlreadyRevealed = 46,
    InvalidRevealWindow = 47,
    HashMismatch = 48,
    OracleNetworkMismatch = 49,
    InvalidProtocolFeeBps = 51,
    MintLimitExceeded = 53,
    NoPendingRotation = 54,
    RotationDelayNotElapsed = 55,
    InvalidArchiveRetention = 62,
    InvalidCommitment = 63,
    InvalidSalt = 64,
    NoRoundTemplate = 65,
    OracleTimestampOutsideWindow = 66,
    EpochBudgetExceeded = 67,
    OracleNotLive = 68,
    InvalidPayoutPolicy = 69,
    BelowMinBet = 70,
    InsufficientOracleQuorum = 71,
    TooFewObservations = 72,
    OracleOutlierRejected = 73,
    DuplicateOracleSource = 74,
    InvalidObservationOrder = 75,
    UnsupportedDataKeyForTtlTouch = 76,
    PendingWinningsNotFound = 77,
    ExpiryNotConfigured = 78,
    AccessDenied = 79,
    ProposalNotFound = 80,
    ProposalExpired = 81,
    GovInvalidState = 82,
    GovUnauthorized = 83,
    IllegalPhaseTransition = 84,
    OracleHeartbeatUnhealthy = 85,
    PendingWinningsNotExpired = 86,
    EarlyCashoutDisabled = 87,
    PositionNotFound = 88,
    InvalidPhaseForCashout = 89,
    WrongModeForCashout = 90,
    ClaimBatchTooLarge = 91,
    DuplicateClaimAddress = 92,
    DisputeWindowExpired = 93,
    ClaimLocked = 94,
    RoundStartLedgerReused = 95,
    InvalidAmount = 96,
    InsuranceInvalidSplit = 97,
    InsuranceInsufficientFund = 98,
    InsuranceEventNotEligible = 99,
}
